[package]
name = "minimalist2"
version = "0.1.0"
authors = ["davidrwen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rand = "0.8.0"
rand_distr = "0.4.0"
dyn-clone = "1.0.4"